### ISSUE TITLE
[Suggeston] Expand the wiki

### ISSUE THREAD

**Issue by EmosewaGamer** [modmuss50/RecipeManipulator#1]
As currently the wiki doesn't have anything about the recipe removal and I cannot seem to figure it out, could you please add that to the wiki?

 You also have no examples with recipes that use more than 1 item in them, nor shapeless recipes.

 Thank you.

**Comment by Joxxs** [comment]
`(string.startsWith("item@") || string.startsWith("block@") && string.contains(":"))`

so in remove you would have something like ['block@minecraft:chest', 'item@minecraft:wooden_pickaxe']

block/item part doesn't currently do anything but parsing requires it and could be used for future update.

**Comment by EmosewaGamer** [comment]
What about meta data?

**Comment by Joxxs** [comment]
None that I know of , you might just have to add the recipe back for the specific meta item you wish recipes are completely based off forge itself

https://gist.github.com/LexManos/2a11d4f7aa9d680d861dae4faf9dcfa6

and search for item to remove isn't checking meta data or nbt

**Comment by EmosewaGamer** [comment]
Ok, maybe that Gist would have been more helpful when it is the same thing.

 Anyways, I started adding recipes and I don't get what I'm doing wrong:
 Crash: https://pastebin.com/2pWKgPjK
 On of my recipes: https://pastebin.com/ZsvctTq4

 And I did already specify Steel.

**Comment by MysticAura** [comment]
The crash log indicates the problem was with constants, so it would be helpful to show your _constants.json file which sets the steel variable info. It appears as if you didn't use the oredict entry correctly.

**Comment by modmuss50** [comment]
Yeah, the game will crash if you have an invalid recipe or constants file.

**Comment by EmosewaGamer** [comment]
And what I don't get is why you require constants in the first place. I wanted to do it without constants, but the game simply crashed because i didn't have any.

**Comment by MysticAura** [comment]
If you don't want to use any constants, you could just leave _constants blank aside from []

If you do want to use it, then I think their shouldn't be square brackets around the ingredients section.

**Comment by modmuss50** [comment]
I have put some more examples on the curse page, and I have added support for removing recipes based on the meta data of items/blocks. If you have any more questions the best place to ask is on our discord server.
